name: bloc_architecture_app
description: A Flutetr Bloc Architecture project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^1.7.5
  bloc: ^6.1.1
  cupertino_icons: ^1.0.0
  device_preview: ^0.6.2-beta
  flare_flutter: ^2.0.6
  flutter_bloc: ^6.1.1
  hydrated_bloc: ^6.1.0
  simple_animations: ^2.5.1
  sizer: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/flare/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
